### ISSUE TITLE
LootMan steals all items in Virgil's cave (Virgil's Laboratory). Also causes crash when the LootMan tries to "Steal" items on Virgil's Container Lootbox / Boss loot container.

### ISSUE THREAD

**Issue by amirullahizzan** [eideehi/fo4-lootman#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

2.0.5

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### What happened?

Not sure if it's an interaction with another mod. I was using 2.0.4 during the bug. and I also have the problem on the newest 2.0.5 version. I have my LootMan on. 
Although, it doesn't look like it's caused by interaction with other mods.

LootMan steals all items in Virgil's cave (Virgil's Laboratory).
Also causes crash when the LootMan tries to "Steal" items on Virgil's Container Lootbox / Boss loot container.

This crash was also reported by another guy in Nexusmod here https://www.nexusmods.com/fallout4/mods/42443?tab=bugs by Ractaros96

Disabling Lootman temporarily solves the problem though

### Steps to reproduce the bug

1. Go to Virgil's Laboratory
2. Walk near any item Red text items (Stealable) and LootMan will steal all the items

**Comment by eideehi** [comment]
Thank you for submitting the bug report. This bug, like #2, seems to be caused by LootMan trying to play an animation of a container owned by someone else.

I will investigate how to correctly identify stolen goods.

**Comment by eideehi** [comment]
Fixing the f4se plugin seems to take a long time, so I fixed it with a Papyrus script. With v2.0.6 you will no longer be stealing items from Virgil's Laboratory.
